import {
  Factory,
  Hotel,
  Wind,
  Tractor,
  Sprout,
  CloudFog,
  Building2,
  Cpu,
  Gauge,
  type LucideIcon,
} from "lucide-react";

export type ProductCategory = {
  slug: string;
  title: string;
  /** Short label for nav / cards. */
  menuLabel: string;
  intro: string;
  icon: LucideIcon;
  image?: string;
  /** Related solution vertical slug for cross-linking. */
  verticalSlug?: string;
  /** Product sub-categories offered under this catalog. */
  items: string[];
};

export const productCategories: ProductCategory[] = [
  {
    slug: "industrial-humidification",
    title: "Industrial Humidification — Products & Categories",
    menuLabel: "Industrial Humidification",
    intro:
      "High-pressure fogging and precision humidification hardware engineered for textile, paper, electronics, pharmaceutical, food and warehousing environments.",
    icon: Factory,
    image: "/images/industrial-humidification.jpg",
    verticalSlug: "industrial-humidification",
    items: [
      "Industrial Humidification Systems",
      "High-Pressure Fogging Systems",
      "High-Pressure Pumping Systems",
      "Fogging Nozzles",
      "Nozzle Accessories",
      "High-Pressure Tubing & Piping",
      "Water Filtration Systems",
      "Humidity Control Systems",
      "Industrial Sensors",
      "Automation & Monitoring",
      "Solenoid Valves & Flow Control",
      "Industrial Cooling Systems",
      "Dust Suppression Systems",
      "Cold Storage Humidification",
      "Textile Humidification Systems",
      "Paper & Printing Humidification",
      "Electronics & Cleanroom Humidification",
      "Pharmaceutical Humidification",
      "Wood & Furniture Humidification",
      "Spare Parts & Replacement Components",
    ],
  },
  {
    slug: "resort-hospitality-fogging",
    title: "Resort & Hospitality Fogging — Products & Categories",
    menuLabel: "Resort & Hospitality Fogging",
    intro:
      "Architectural fog and outdoor cooling systems for resorts, hotels, restaurants, poolside decks, rooftops and luxury residences.",
    icon: Hotel,
    image: "/images/resort-hospitality-fogging.jpg",
    verticalSlug: "resort-hospitality-fogging",
    items: [
      "High-Pressure Fogging Systems",
      "Outdoor Cooling Systems",
      "Resort & Hotel Cooling Systems",
      "Restaurant & Café Cooling Systems",
      "Poolside & Beach Cooling Systems",
      "Rooftop Cooling Systems",
      "Event Venue Cooling Systems",
      "Theme Park & Entertainment Cooling",
      "Golf Course Cooling Systems",
      "Spa & Wellness Cooling Systems",
      "Public Space Cooling Systems",
      "Luxury Residential Cooling Systems",
      "Architectural Fog Systems",
      "Smart Automation & Control",
      "High-Pressure Pump Systems",
      "Fogging Nozzles",
      "Water Treatment Systems",
      "Spare Parts & Accessories",
    ],
  },
  {
    slug: "outdoor-cooling-misting",
    title: "Outdoor Cooling & Misting — Products & Categories",
    menuLabel: "Outdoor Cooling & Misting",
    intro:
      "Large-scale evaporative cooling and misting hardware for commercial, industrial, sports, transport and public-infrastructure environments.",
    icon: Wind,
    image: "/images/outdoor-cooling-misting.jpg",
    verticalSlug: "outdoor-cooling-misting",
    items: [
      "Outdoor Cooling Systems",
      "High-Pressure Misting Systems",
      "Restaurant & Hospitality Cooling Systems",
      "Commercial Cooling Systems",
      "Industrial Cooling Systems",
      "Construction Site Cooling Systems",
      "Sports & Stadium Cooling Systems",
      "Public Infrastructure Cooling Systems",
      "Transportation Cooling Systems",
      "Parking & Queue Cooling Systems",
      "Residential Outdoor Cooling Systems",
      "High-Temperature Region Cooling Systems",
      "Smart Automation & Controls",
      "High-Pressure Pump Systems",
      "Fogging Nozzles & Atomizers",
      "Water Treatment Systems",
      "Piping & Distribution Network",
      "Spare Parts & Maintenance",
    ],
  },
  {
    slug: "farm-climate-control",
    title: "Farm Climate Control — Products & Categories",
    menuLabel: "Farm Climate Control",
    intro:
      "Climate control and environmental hardware for poultry, dairy, livestock, mushroom, hatchery and aquaculture operations.",
    icon: Tractor,
    image: "/images/farm-climate-control.jpg",
    verticalSlug: "farm-climate-control",
    items: [
      "Farm Climate Control Systems",
      "Poultry Farm Climate Control Systems",
      "Dairy Farm Climate Control Systems",
      "Livestock Climate Control Systems",
      "Mushroom Climate Control Systems",
      "Hatchery Climate Control Systems",
      "Aquaculture Climate Control Systems",
      "Hydroponic & Green Fodder Systems",
      "Barn & Animal Housing Climate Control",
      "Agricultural Humidification Systems",
      "Agricultural Fogging Systems",
      "Agricultural Dust Suppression Systems",
      "Farm Automation & Environmental Control",
      "High-Pressure Pump Systems",
      "Fogging Nozzles & Accessories",
      "Water Treatment Systems",
      "High-Pressure Piping & Fittings",
      "Environmental Sensors",
      "Spare Parts & Maintenance",
    ],
  },
  {
    slug: "agricultural-misting",
    title: "Agricultural Misting & Humidification — Products & Categories",
    menuLabel: "Agricultural Misting",
    intro:
      "Precision climate control hardware for greenhouses, vertical farms, nurseries, hydroponics and high-value crop cultivation.",
    icon: Sprout,
    image: "/images/agricultural-misting.jpg",
    verticalSlug: "agricultural-misting",
    items: [
      "Agricultural Climate Control Systems",
      "Greenhouse & Polyhouse Climate Control Systems",
      "Vertical Farming Climate Control Systems",
      "Nursery & Plant Propagation Systems",
      "High-Value Crop Climate Control Systems",
      "Vineyard & Orchard Cooling Systems",
      "Hydroponic & Aeroponic Climate Control Systems",
      "Shade Net Farming Climate Systems",
      "Indoor Farming Climate Control Systems",
      "Seed Germination & Research Climate Systems",
      "Botanical Garden & Conservatory Climate Systems",
      "Mushroom Farming Climate Control Systems",
      "Agricultural High-Pressure Fogging Systems",
      "Agricultural Humidification Systems",
      "Environmental Monitoring & Automation",
      "High-Pressure Pump Systems",
      "Fogging Nozzles & Accessories",
      "Water Treatment Systems",
      "High-Pressure Piping & Distribution",
      "Environmental Sensors",
      "Spare Parts & Maintenance",
    ],
  },
  {
    slug: "dust-suppression",
    title: "Dust Suppression — Products & Categories",
    menuLabel: "Dust Suppression",
    intro:
      "Ultra-high-pressure dust suppression hardware for mining, crushing, cement, coal handling, ports, steel and construction operations.",
    icon: CloudFog,
    image: "/images/dust-suppression.jpg",
    verticalSlug: "dust-suppression",
    items: [
      "High-Pressure Dust Suppression Systems",
      "Mining & Quarry Dust Suppression",
      "Stone Crusher Dust Suppression Systems",
      "Cement Plant Dust Suppression Systems",
      "Coal Handling Dust Suppression Systems",
      "Port & Bulk Material Handling Dust Suppression",
      "Steel Plant & Foundry Dust Suppression",
      "Construction & Demolition Dust Suppression",
      "Waste Management & Recycling Dust Suppression",
      "Stockyard & Conveyor Dust Suppression",
      "Dust Monitoring & Automation Systems",
      "High-Pressure Pumping Systems",
      "Fogging Nozzles & Atomization Components",
      "High-Pressure Piping & Installation Accessories",
      "Water Filtration Systems",
      "Solenoid Valves & Control Components",
      "Environmental Sensors",
      "Custom Engineered Dust Suppression Solutions",
    ],
  },
  {
    slug: "hvac",
    title: "Industrial HVAC Systems — Products & Categories",
    menuLabel: "Industrial HVAC",
    intro:
      "Complete HVAC, air-handling, ventilation, filtration, cooling and automation product range for industrial and commercial facilities.",
    icon: Building2,
    image: "/images/facility-banner.jpg",
    verticalSlug: "hvac-building-control",
    items: [
      "HVAC Systems (Central AC, Chilled Water, VRF/VRV, DX)",
      "Air Handling Equipment (AHU, FAHU, FCU, RTU)",
      "Ventilation Systems",
      "Cleanroom & Controlled Environments",
      "Filtration Systems",
      "Humidification Systems",
      "Dehumidification Systems",
      "Industrial Cooling Systems",
      "Evaporative Cooling Systems",
      "Process Cooling",
      "Air Distribution Systems (Ducting, Dampers, Terminals)",
      "Industrial Fans",
      "Pumping Systems",
      "HVAC Automation (PLC, BMS, SCADA)",
      "Energy Management",
      "Indoor Air Quality (IAQ)",
      "HVAC Controls",
      "Refrigeration Systems",
      "Engineering Services",
      "Smart HVAC Technologies",
    ],
  },
  {
    slug: "industrial-automation",
    title: "Industrial Automation & Custom Control Panels — Products & Categories",
    menuLabel: "Automation & Control Panels",
    intro:
      "Custom-engineered PLC, HMI, SCADA, IIoT and electrical control panels for every industrial process and utility.",
    icon: Cpu,
    image: "/images/product-pump-unit.jpg",
    verticalSlug: "industrial-automation",
    items: [
      "PLC Automation Systems",
      "HMI & Operator Interface Systems",
      "SCADA & Industrial Monitoring Systems",
      "Industrial IoT (IIoT) Solutions",
      "Motor Control Panels (MCC)",
      "Power Distribution & PCC Panels",
      "Variable Frequency Drive (VFD) Panels",
      "Soft Starter Panels",
      "Pump Automation Systems",
      "Water Treatment Automation Panels",
      "HVAC Automation Panels",
      "Building Management System (BMS)",
      "Environmental Control Panels",
      "Industrial Process Control Panels",
      "Conveyor & Material Handling Automation",
      "Manufacturing Automation Panels",
      "Energy Monitoring Systems",
      "Instrumentation Panels",
      "Safety & Protection Panels",
      "Utility Automation Panels",
      "Communication & Networking Panels",
      "Custom Electrical Panels",
      "Smart Monitoring & AI Solutions",
      "Complete Turnkey Automation Solutions",
    ],
  },
  {
    slug: "h-plant",
    title: "Humidity Plant (H-Plant) — Products & Categories",
    menuLabel: "Humidity Plant Systems",
    intro:
      "Large-scale centralized humidity plants and evaporative cooling systems for textile, tobacco and process industries.",
    icon: Gauge,
    image: "/images/facility-banner.jpg",
    verticalSlug: "h-plant",
    items: [
      "Industrial Humidification Systems",
      "Industrial Cooling Systems",
      "Cooling Tower Systems",
      "Chilled Water Systems",
      "Air Handling Systems",
      "Air Distribution Systems",
      "Water Treatment Systems",
      "High-Pressure Fogging Systems",
      "Pumping Systems",
      "Automation & Smart Controls",
      "Sensors & Instrumentation",
      "Ventilation Systems",
      "Industrial Air Washer Systems",
      "Complete Turnkey Systems",
      "Spare Parts & Accessories",
    ],
  },
];

export function getProductCategory(slug: string): ProductCategory | undefined {
  return productCategories.find((c) => c.slug === slug);
}
